export const Categories = [
  "Cardiologist",
  "Dermatologist",
  "Neurologist",
  "Pediatrician",
  "Psychiatrist",
  "Radiologist",
  "Anesthesiologist",
  "Endocrinologist",
  "Gastroenterologist",
  "Hematologist",
  "Oncologist",
  "Ophthalmologist",
  "Orthopedic Surgeon",
  "Obstetrician/Gynecologist",
  "Pathologist",
  "Plastic Surgeon",
  "Pulmonologist",
  "Rheumatologist",
  "Urologist",
  "Nephrologist",
  "Infectious Disease Specialist",
  "Allergist/Immunologist",
  "General Surgeon",
  "Family Medicine Physician",
  "Internal Medicine Physician",
  "Geriatrician",
  "Sports Medicine Physician",
  "Emergency Medicine Physician",
  "Podiatrist",
  "Chiropractor",
  "Otolaryngologist (ENT)",
];

export const doctors = [
  {
    name: "Dr. Sarah Johnson",
    appointmentTime: "10:00 AM - 12:00 PM",
    fees: 100,
    category: "Cardiologist",
    hospital: "City Heart Clinic",
    gender: "Female",
    id: 1,
  },
  {
    name: "Dr. John Lee",
    appointmentTime: "2:00 PM - 4:00 PM",
    fees: 120,
    category: "Dermatologist",
    hospital: "Skin Care Center",
    gender: "Male",
    id: 2,
  },
  {
    name: "Dr. Rachel Kim",
    appointmentTime: "9:00 AM - 11:00 AM",
    fees: 90,
    category: "Neurologist",
    hospital: "Brain Health Institute",
    gender: "Female",
    id: 3,
  },
  {
    name: "Dr. Michael Chen",
    appointmentTime: "3:00 PM - 5:00 PM",
    fees: 150,
    category: "Pediatrician",
    hospital: "Kids Care Hospital",
    gender: "Male",
    id: 4,
  },
  {
    name: "Dr. Emily Brown",
    appointmentTime: "11:00 AM - 1:00 PM",
    fees: 110,
    category: "Psychiatrist",
    hospital: "Mental Wellness Center",
    gender: "Female",
    id: 5,
  },
  {
    name: "Dr. David Anderson",
    appointmentTime: "1:00 PM - 3:00 PM",
    fees: 140,
    category: "Radiologist",
    hospital: "Radiology Plus",
    gender: "Male",
    id: 6,
  },
  {
    name: "Dr. Susan Moore",
    appointmentTime: "10:30 AM - 12:30 PM",
    fees: 130,
    category: "Endocrinologist",
    hospital: "Hormone Health Clinic",
    gender: "Female",
    id: 7,
  },
  {
    name: "Dr. Steven White",
    appointmentTime: "4:00 PM - 6:00 PM",
    fees: 160,
    category: "Orthopedic Surgeon",
    hospital: "OrthoPlus Hospital",
    gender: "Male",
    id: 8,
  },
  {
    name: "Dr. Anna Patel",
    appointmentTime: "8:00 AM - 10:00 AM",
    fees: 95,
    category: "Obstetrician/Gynecologist",
    hospital: "Women’s Health Clinic",
    gender: "Female",
    id: 9,
  },
  {
    name: "Dr. Robert Thompson",
    appointmentTime: "12:00 PM - 2:00 PM",
    fees: 105,
    category: "Gastroenterologist",
    hospital: "Digestive Health Institute",
    gender: "Male",
    id: 10,
  },
  {
    name: "Dr. Sarah Johnson",
    appointmentTime: "10:00 AM - 12:00 PM",
    fees: 100,
    category: "Cardiologist",
    hospital: "City Heart Clinic",
    gender: "Female",
    id: 11,
  },
  {
    name: "Dr. John Lee",
    appointmentTime: "2:00 PM - 4:00 PM",
    fees: 120,
    category: "Dermatologist",
    hospital: "Skin Care Center",
    gender: "Male",
    id: 12,
  },
  {
    name: "Dr. Rachel Kim",
    appointmentTime: "9:00 AM - 11:00 AM",
    fees: 90,
    category: "Neurologist",
    hospital: "Brain Health Institute",
    gender: "Female",
    id: 13,
  },
  {
    name: "Dr. Michael Chen",
    appointmentTime: "3:00 PM - 5:00 PM",
    fees: 150,
    category: "Pediatrician",
    hospital: "Kids Care Hospital",
    gender: "Male",
    id: 14,
  },
  {
    name: "Dr. Emily Brown",
    appointmentTime: "11:00 AM - 1:00 PM",
    fees: 110,
    category: "Psychiatrist",
    hospital: "Mental Wellness Center",
    gender: "Female",
    id: 15,
  },
  {
    name: "Dr. David Anderson",
    appointmentTime: "1:00 PM - 3:00 PM",
    fees: 140,
    category: "Radiologist",
    hospital: "Radiology Plus",
    gender: "Male",
    id: 16,
  },
  {
    name: "Dr. Susan Moore",
    appointmentTime: "10:30 AM - 12:30 PM",
    fees: 130,
    category: "Endocrinologist",
    hospital: "Hormone Health Clinic",
    gender: "Female",
    id: 17,
  },
  {
    name: "Dr. Steven White",
    appointmentTime: "4:00 PM - 6:00 PM",
    fees: 160,
    category: "Orthopedic Surgeon",
    hospital: "OrthoPlus Hospital",
    gender: "Male",
    id: 18,
  },
  {
    name: "Dr. Anna Patel",
    appointmentTime: "8:00 AM - 10:00 AM",
    fees: 95,
    category: "Obstetrician/Gynecologist",
    hospital: "Women’s Health Clinic",
    gender: "Female",
    id: 19,
  },
  {
    name: "Dr. Robert Thompson",
    appointmentTime: "12:00 PM - 2:00 PM",
    fees: 105,
    category: "Gastroenterologist",
    hospital: "Digestive Health Institute",
    gender: "Male",
    id: 20,
  },
];

export const currentUser = {
  name: "Arsalan Ali",
  role: "doctor",
  email: "arsal@gmail.com",
};

export const appointments = [
  {
    user: {
      name: "Alice Smith",
      email: "alice.smith@example.com",
    },
    appointmentTime: "10:00 AM - 12:00 PM",
    status: "Confirmed",
    appointmentDate: "2024-11-05",
    doctor: {
      name: "Dr. Sarah Johnson",
      hospital: "City Heart Clinic",
    },
  },
  {
    user: {
      name: "Bob Williams",
      email: "bob.williams@example.com",
    },
    appointmentTime: "2:00 PM - 4:00 PM",
    status: "Pending",
    appointmentDate: "2024-11-06",
    doctor: {
      name: "Dr. John Lee",
      hospital: "Skin Care Center",
    },
  },
  {
    user: {
      name: "Charlie Davis",
      email: "charlie.davis@example.com",
    },
    appointmentTime: "9:00 AM - 11:00 AM",
    status: "Confirmed",
    appointmentDate: "2024-11-07",
    doctor: {
      name: "Dr. Rachel Kim",
      hospital: "Brain Health Institute",
    },
  },
  {
    user: {
      name: "Diana Evans",
      email: "diana.evans@example.com",
    },
    appointmentTime: "3:00 PM - 5:00 PM",
    status: "Canceled",
    appointmentDate: "2024-11-08",
    doctor: {
      name: "Dr. Michael Chen",
      hospital: "Kids Care Hospital",
    },
  },
  {
    user: {
      name: "Edward Johnson",
      email: "edward.johnson@example.com",
    },
    appointmentTime: "11:00 AM - 1:00 PM",
    status: "Confirmed",
    appointmentDate: "2024-11-09",
    doctor: {
      name: "Dr. Emily Brown",
      hospital: "Mental Wellness Center",
    },
  },
  {
    user: {
      name: "Fiona Carter",
      email: "fiona.carter@example.com",
    },
    appointmentTime: "1:00 PM - 3:00 PM",
    status: "Pending",
    appointmentDate: "2024-11-10",
    doctor: {
      name: "Dr. David Anderson",
      hospital: "Radiology Plus",
    },
  },
  {
    user: {
      name: "George Harris",
      email: "george.harris@example.com",
    },
    appointmentTime: "10:30 AM - 12:30 PM",
    status: "Confirmed",
    appointmentDate: "2024-11-11",
    doctor: {
      name: "Dr. Susan Moore",
      hospital: "Hormone Health Clinic",
    },
  },
  {
    user: {
      name: "Hannah Lewis",
      email: "hannah.lewis@example.com",
    },
    appointmentTime: "4:00 PM - 6:00 PM",
    status: "Confirmed",
    appointmentDate: "2024-11-12",
    doctor: {
      name: "Dr. Steven White",
      hospital: "OrthoPlus Hospital",
    },
  },
  {
    user: {
      name: "Ian Walker",
      email: "ian.walker@example.com",
    },
    appointmentTime: "8:00 AM - 10:00 AM",
    status: "Pending",
    appointmentDate: "2024-11-13",
    doctor: {
      name: "Dr. Anna Patel",
      hospital: "Women’s Health Clinic",
    },
  },
  {
    user: {
      name: "Jessica Green",
      email: "jessica.green@example.com",
    },
    appointmentTime: "12:00 PM - 2:00 PM",
    status: "Confirmed",
    appointmentDate: "2024-11-14",
    doctor: {
      name: "Dr. Robert Thompson",
      hospital: "Digestive Health Institute",
    },
  },
];
